# Site settings
title: Ben Cipollini
tagline: All computation, all the time.
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl: '/folio'
url:  # the base hostname & protocol for your site


# Contact settings
email: bcipolli@ucsd.edu
twitter_username: mrquickowl
tumblr_username: mrquickowl
github_username:  bcipolli
linkedin_url: http://foo

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 5
paginate_path: "/blog/page:num"


# blog, code, pubs, projects, mentoring, about,
collections:
  projects:
    output: true
    permalink: /projects/:path
  news:
    output: true
    permalink: /news/:path

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project