# Site settings
title: Ben Cipollini
tagline: All computation, all the time.
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl: ''
url:  # the base hostname & protocol for your site


# Contact settings
email: bcipolli@ucsd.edu
twitter_username: mrquickowl
tumblr_username: mrquickowl
github_username:  bcipolli
linkedin_url: https://www.linkedin.com/in/dr-ben-cipollini-217709b
facebook_username: bcipolli
researchgate_username: Ben_Cipollini
redbubble_username: quickowl
googlescholar_url: folio
googleplus_url: folio
wordpress_url: folio

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 5
paginate_path: "/publications/page:num"


# blog, code, pubs, projects, mentoring, about,
collections:
  projects:
    output: true
    permalink: /projects/:path
  news:
    output: true
    permalink: /news/:path
  publication-types:
    output: true
    permalink: /publications/:path

defaults:
  - scope:
      type: projects
    values:
      layout: project
      document-class: projects
  - scope:
      type: posts
    values:
      layout: post
      document-class: blog
  - scope:
      type: publications
    values:
      layout: publications-list
      document-class: projects
